# Generated by Django 4.0.6 on 2022-08-29 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coment',
        ),
    ]
